config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :candidates
  resources :jobs
  resources :type_contractions
  resources :companies
  resources :departments
  root 'home#index'
  get 'welcome/index'
  devise_for :admin, 
              path:  'admin', 
              path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }, 
              controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: 'admins/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :job
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :department
  belongs_to :company
  belongs_to :type_contraction
end

app/models/type_contraction.rb
class TypeContraction < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "website"
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name_job, :department_id, :company_id, :type_contraction_id, :role, :description, :mean_activity, :requirement, :desirable, :email_send_cv, :salary, :benefits, :english, :spanish, :quantity_vacancy, :end_date, :job_filled, :slug, :img1, :inactive)
    end
end

app/controllers/type_contractions_controller.rb
class TypeContractionsController < ApplicationController
  before_action :set_type_contraction, only: [:show, :edit, :update, :destroy]

  # GET /type_contractions
  # GET /type_contractions.json
  def index
    @type_contractions = TypeContraction.all
  end

  # GET /type_contractions/1
  # GET /type_contractions/1.json
  def show
  end

  # GET /type_contractions/new
  def new
    @type_contraction = TypeContraction.new
  end

  # GET /type_contractions/1/edit
  def edit
  end

  # POST /type_contractions
  # POST /type_contractions.json
  def create
    @type_contraction = TypeContraction.new(type_contraction_params)

    respond_to do |format|
      if @type_contraction.save
        format.html { redirect_to @type_contraction, notice: 'Type contraction was successfully created.' }
        format.json { render :show, status: :created, location: @type_contraction }
      else
        format.html { render :new }
        format.json { render json: @type_contraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_contractions/1
  # PATCH/PUT /type_contractions/1.json
  def update
    respond_to do |format|
      if @type_contraction.update(type_contraction_params)
        format.html { redirect_to @type_contraction, notice: 'Type contraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_contraction }
      else
        format.html { render :edit }
        format.json { render json: @type_contraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_contractions/1
  # DELETE /type_contractions/1.json
  def destroy
    @type_contraction.destroy
    respond_to do |format|
      format.html { redirect_to type_contractions_url, notice: 'Type contraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_contraction
      @type_contraction = TypeContraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_contraction_params
      params.require(:type_contraction).permit(:name, :variable_name, :description, :inactive, :slug)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/type_contractions_helper.rb
module TypeContractionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/type_contractions/_form.html.erb
<%= form_with(model: type_contraction, local: true) do |form| %>
  <% if type_contraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_contraction.errors.count, "error") %> prohibited this type_contraction from being saved:</h2>

      <ul>
      <% type_contraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :variable_name %>
    <%= form.text_field :variable_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :inactive %>
    <%= form.check_box :inactive %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_contractions/edit.html.erb
<h1>Editing Type Contraction</h1>

<%= render 'form', type_contraction: @type_contraction %>

<%= link_to 'Show', @type_contraction %> |
<%= link_to 'Back', type_contractions_path %>

app/views/type_contractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Contractions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Variable name</th>
      <th>Description</th>
      <th>Inactive</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_contractions.each do |type_contraction| %>
      <tr>
        <td><%= type_contraction.name %></td>
        <td><%= type_contraction.variable_name %></td>
        <td><%= type_contraction.description %></td>
        <td><%= type_contraction.inactive %></td>
        <td><%= type_contraction.slug %></td>
        <td><%= link_to 'Show', type_contraction %></td>
        <td><%= link_to 'Edit', edit_type_contraction_path(type_contraction) %></td>
        <td><%= link_to 'Destroy', type_contraction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Contraction', new_type_contraction_path %>

app/views/type_contractions/new.html.erb
<h1>New Type Contraction</h1>

<%= render 'form', type_contraction: @type_contraction %>

<%= link_to 'Back', type_contractions_path %>

app/views/type_contractions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_contraction.name %>
</p>

<p>
  <strong>Variable name:</strong>
  <%= @type_contraction.variable_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @type_contraction.description %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @type_contraction.inactive %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @type_contraction.slug %>
</p>

<%= link_to 'Edit', edit_type_contraction_path(@type_contraction) %> |
<%= link_to 'Back', type_contractions_path %>