config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :candidates
  resources :jobs
  resources :type_contractions
  resources :companies
  resources :departments
  root 'home#index'
  get 'welcome/index'
  devise_for :admin, 
              path:  'admin', 
              path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }, 
              controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: 'admins/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :job
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :department
  belongs_to :company
  belongs_to :type_contraction
end

app/models/type_contraction.rb
class TypeContraction < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:fullname, :email, :cellphone, :date_birth, :gender, :job_id, :file, :linkedin, :portfolio, :short_description, :accepted, :available_change_city, :license_car, :type_license_car, :have_car, :city, :state, :country, :slug, :good_profile, :observation)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message, :accepted, :newsletter, :slug)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "website"
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name_job, :department_id, :company_id, :type_contraction_id, :role, :description, :mean_activity, :requirement, :desirable, :email_send_cv, :salary, :benefits, :english, :spanish, :quantity_vacancy, :end_date, :job_filled, :slug, :img1, :inactive)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cellphone %>
    <%= form.text_field :cellphone %>
  </div>

  <div class="field">
    <%= form.label :date_birth %>
    <%= form.date_select :date_birth %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :job_id %>
    <%= form.text_field :job_id %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.text_field :file %>
  </div>

  <div class="field">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin %>
  </div>

  <div class="field">
    <%= form.label :portfolio %>
    <%= form.text_field :portfolio %>
  </div>

  <div class="field">
    <%= form.label :short_description %>
    <%= form.text_area :short_description %>
  </div>

  <div class="field">
    <%= form.label :accepted %>
    <%= form.check_box :accepted %>
  </div>

  <div class="field">
    <%= form.label :available_change_city %>
    <%= form.check_box :available_change_city %>
  </div>

  <div class="field">
    <%= form.label :license_car %>
    <%= form.check_box :license_car %>
  </div>

  <div class="field">
    <%= form.label :type_license_car %>
    <%= form.text_field :type_license_car %>
  </div>

  <div class="field">
    <%= form.label :have_car %>
    <%= form.check_box :have_car %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :good_profile %>
    <%= form.check_box :good_profile %>
  </div>

  <div class="field">
    <%= form.label :observation %>
    <%= form.text_field :observation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Email</th>
      <th>Cellphone</th>
      <th>Date birth</th>
      <th>Gender</th>
      <th>Job</th>
      <th>File</th>
      <th>Linkedin</th>
      <th>Portfolio</th>
      <th>Short description</th>
      <th>Accepted</th>
      <th>Available change city</th>
      <th>License car</th>
      <th>Type license car</th>
      <th>Have car</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Slug</th>
      <th>Good profile</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.fullname %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.cellphone %></td>
        <td><%= candidate.date_birth %></td>
        <td><%= candidate.gender %></td>
        <td><%= candidate.job %></td>
        <td><%= candidate.file %></td>
        <td><%= candidate.linkedin %></td>
        <td><%= candidate.portfolio %></td>
        <td><%= candidate.short_description %></td>
        <td><%= candidate.accepted %></td>
        <td><%= candidate.available_change_city %></td>
        <td><%= candidate.license_car %></td>
        <td><%= candidate.type_license_car %></td>
        <td><%= candidate.have_car %></td>
        <td><%= candidate.city %></td>
        <td><%= candidate.state %></td>
        <td><%= candidate.country %></td>
        <td><%= candidate.slug %></td>
        <td><%= candidate.good_profile %></td>
        <td><%= candidate.observation %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @candidate.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @candidate.cellphone %>
</p>

<p>
  <strong>Date birth:</strong>
  <%= @candidate.date_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @candidate.gender %>
</p>

<p>
  <strong>Job:</strong>
  <%= @candidate.job %>
</p>

<p>
  <strong>File:</strong>
  <%= @candidate.file %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @candidate.linkedin %>
</p>

<p>
  <strong>Portfolio:</strong>
  <%= @candidate.portfolio %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @candidate.short_description %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @candidate.accepted %>
</p>

<p>
  <strong>Available change city:</strong>
  <%= @candidate.available_change_city %>
</p>

<p>
  <strong>License car:</strong>
  <%= @candidate.license_car %>
</p>

<p>
  <strong>Type license car:</strong>
  <%= @candidate.type_license_car %>
</p>

<p>
  <strong>Have car:</strong>
  <%= @candidate.have_car %>
</p>

<p>
  <strong>City:</strong>
  <%= @candidate.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @candidate.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @candidate.country %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @candidate.slug %>
</p>

<p>
  <strong>Good profile:</strong>
  <%= @candidate.good_profile %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @candidate.observation %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>