config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :candidates
  resources :jobs
  resources :type_contractions
  resources :companies
  resources :departments
  root 'home#index'
  get 'welcome/index'
  devise_for :admin, 
              path:  'admin', 
              path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }, 
              controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: 'admins/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :job
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :department
  belongs_to :company
  belongs_to :type_contraction
end

app/models/type_contraction.rb
class TypeContraction < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :variable_name, :description, :inactive, :slug)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message, :accepted, :newsletter, :slug)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "website"
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name_job, :department_id, :company_id, :type_contraction_id, :role, :description, :mean_activity, :requirement, :desirable, :email_send_cv, :salary, :benefits, :english, :spanish, :quantity_vacancy, :end_date, :job_filled, :slug, :img1, :inactive)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :variable_name %>
    <%= form.text_field :variable_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :inactive %>
    <%= form.check_box :inactive %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Variable name</th>
      <th>Description</th>
      <th>Inactive</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.variable_name %></td>
        <td><%= company.description %></td>
        <td><%= company.inactive %></td>
        <td><%= company.slug %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Variable name:</strong>
  <%= @company.variable_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @company.inactive %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @company.slug %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_job %>
    <%= form.text_field :name_job %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.text_field :department_id %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :type_contraction_id %>
    <%= form.text_field :type_contraction_id %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :mean_activity %>
    <%= form.text_field :mean_activity %>
  </div>

  <div class="field">
    <%= form.label :requirement %>
    <%= form.text_field :requirement %>
  </div>

  <div class="field">
    <%= form.label :desirable %>
    <%= form.text_field :desirable %>
  </div>

  <div class="field">
    <%= form.label :email_send_cv %>
    <%= form.text_field :email_send_cv %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary %>
  </div>

  <div class="field">
    <%= form.label :benefits %>
    <%= form.text_field :benefits %>
  </div>

  <div class="field">
    <%= form.label :english %>
    <%= form.text_field :english %>
  </div>

  <div class="field">
    <%= form.label :spanish %>
    <%= form.text_field :spanish %>
  </div>

  <div class="field">
    <%= form.label :quantity_vacancy %>
    <%= form.number_field :quantity_vacancy %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :job_filled %>
    <%= form.check_box :job_filled %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :img1 %>
    <%= form.text_field :img1 %>
  </div>

  <div class="field">
    <%= form.label :inactive %>
    <%= form.check_box :inactive %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Name job</th>
      <th>Department</th>
      <th>Company</th>
      <th>Type contraction</th>
      <th>Role</th>
      <th>Description</th>
      <th>Mean activity</th>
      <th>Requirement</th>
      <th>Desirable</th>
      <th>Email send cv</th>
      <th>Salary</th>
      <th>Benefits</th>
      <th>English</th>
      <th>Spanish</th>
      <th>Quantity vacancy</th>
      <th>End date</th>
      <th>Job filled</th>
      <th>Slug</th>
      <th>Img1</th>
      <th>Inactive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name_job %></td>
        <td><%= job.department %></td>
        <td><%= job.company %></td>
        <td><%= job.type_contraction %></td>
        <td><%= job.role %></td>
        <td><%= job.description %></td>
        <td><%= job.mean_activity %></td>
        <td><%= job.requirement %></td>
        <td><%= job.desirable %></td>
        <td><%= job.email_send_cv %></td>
        <td><%= job.salary %></td>
        <td><%= job.benefits %></td>
        <td><%= job.english %></td>
        <td><%= job.spanish %></td>
        <td><%= job.quantity_vacancy %></td>
        <td><%= job.end_date %></td>
        <td><%= job.job_filled %></td>
        <td><%= job.slug %></td>
        <td><%= job.img1 %></td>
        <td><%= job.inactive %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name job:</strong>
  <%= @job.name_job %>
</p>

<p>
  <strong>Department:</strong>
  <%= @job.department %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Type contraction:</strong>
  <%= @job.type_contraction %>
</p>

<p>
  <strong>Role:</strong>
  <%= @job.role %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Mean activity:</strong>
  <%= @job.mean_activity %>
</p>

<p>
  <strong>Requirement:</strong>
  <%= @job.requirement %>
</p>

<p>
  <strong>Desirable:</strong>
  <%= @job.desirable %>
</p>

<p>
  <strong>Email send cv:</strong>
  <%= @job.email_send_cv %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<p>
  <strong>Benefits:</strong>
  <%= @job.benefits %>
</p>

<p>
  <strong>English:</strong>
  <%= @job.english %>
</p>

<p>
  <strong>Spanish:</strong>
  <%= @job.spanish %>
</p>

<p>
  <strong>Quantity vacancy:</strong>
  <%= @job.quantity_vacancy %>
</p>

<p>
  <strong>End date:</strong>
  <%= @job.end_date %>
</p>

<p>
  <strong>Job filled:</strong>
  <%= @job.job_filled %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @job.slug %>
</p>

<p>
  <strong>Img1:</strong>
  <%= @job.img1 %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @job.inactive %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>