config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :candidates
  resources :jobs
  resources :type_contractions
  resources :companies
  resources :departments
  root 'home#index'
  get 'welcome/index'
  devise_for :admin, 
              path:  'admin', 
              path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }, 
              controllers: { sessions: "admins/sessions", registrations: "admins/registrations", passwords: 'admins/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :job
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :department
  belongs_to :company
  belongs_to :type_contraction
end

app/models/type_contraction.rb
class TypeContraction < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "website"
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name_job, :department_id, :company_id, :type_contraction_id, :role, :description, :mean_activity, :requirement, :desirable, :email_send_cv, :salary, :benefits, :english, :spanish, :quantity_vacancy, :end_date, :job_filled, :slug, :img1, :inactive)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/shared/website/footer/_center.html.erb
<div class="footer-center">
	<h3>Company</h3>
	<p class="footer-company-about">
		Example
	</p>

	<p class="footer-links">

	</p>

	<div class="footer-icons">

	</div>
	
	<p class="footer-company-name mt-3">
		Copyright &copy; <%= Time.current.year %> Reflow
	</p>
</div>

app/views/layouts/shared/website/footer/_footer.html.erb
<!-- The content of your page would go here. -->
<footer class="footer-distributed">
	<div class="container top-buffer bottom-buffer">
	<%= render './layouts/shared/website/footer/left' %>
	<%= render './layouts/shared/website/footer/center' %>
	<%#= render './layouts/shared/website/footer/form_newsletter', 
	newsletter: @newsletter %>
	</div>
</footer>

app/views/layouts/shared/website/footer/_form_newsletter.html.erb
<% if @v_intern_company.newsletter %>
	<div class="footer-right px-3">
		<h3 class='mb-3'>Newsletter</h3>
		<%= form_with(model: newsletter, url: create_newsletter_path, local: true, class: '') do |f| %>
		
			<%= f.text_field :name, class: 'col-md-12 col-12 required', placeholder: t('full_name'), required: true, pattern: '.{3,}', maxlength: 40, minlength: 3 %>
			
			<%= f.text_field :email, class: 'col-md-12 col-12 required', placeholder: 'Email', required: true, pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', maxlength: 40, minlength: 7 %>
			
			<%= f.button t('send'), class: 'col-md-12 col-12' %>
			
	    <button type="button" class="btn btn-secondary col-md-12 col-12 mt-3" data-toggle="modal" data-target="#ModalCancelNewsletter">
	      <%= t('cancel_newsletter') %>
	    </button>
	    
		<% end %>
		<%= render './layouts/shared/website/form/cancel_newsletter' %>
	</div>
<% end %>

app/views/layouts/shared/website/footer/_google_maps.html.erb
<div class="google_maps mt-5 mb--80">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d45079.49557854899!2d7.551143502905613!3d45.07629241458966!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8360b2bf945a04b6!2sMcDonald&#39;s+Torino+Castello!5e0!3m2!1sit!2sit!4v1544105954415" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/layouts/shared/website/footer/_left.html.erb
<div class="footer-left">
	<%= link_to :root, :class => 'tc op80' do %>
		<h3>
			<div class="box" id="box1">Re</div>
			<div class="box" id="box2">Flow</div>
		</h3>
	<% end %>
	
	<p class="footer-links">

	</p>

	<p class="footer-company-name">
		Powered by 
		<a href="https://github.com/souzaleandror" target="_Blank">
			SouzaLeandroR &copy; <%= Time.current.year %> 
		</a>
	</p>
	<p>
		<%= link_to 'Login', admin_session_path, class: 'tc', target: 'blank' %>
	</p>
</div>

app/views/layouts/shared/website/form/_cancel_newsletter.html.erb
<!-- Modal -->
<div class="modal fade" id="ModalCancelNewsletter" tabindex="-1" role="dialog" aria-labelledby="exampleCancelNewsletter" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleCancelNewsletter">
          <%= t('cancel_newsletter') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(:newsletter, local: true, url: cancel_newsletter_path, html: { method: :post, id: 'form_cancel_newsletter' }) do |f| %>
          <div class="col-auto">
            <label class="sr-only" for="form_cancel_newsletter_email">
              <%= t('email') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-envelope"></i>
                </div>
              </div>
              <%= f.email_field :email, class: 'form-control', autocomplete: 'email', placeholder: t('p_email'), required: true, pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', maxlength: 64, minlength: 7, id: 'form_cancel_newsletter_email', 'data-purpose' => 'email', 'aria-invalid' => 'true' %>
            </div>
          </div>
          
          <div class="col-auto text-center mt-3">
            <%= f.submit t('send'), class: "btn btn-primary w90", id: 'form_cancel_newsletter_btn_cancel_newsletter' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <%= t('close') %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/website/form/_forget_password.html.erb
<!-- Modal -->
<div class="modal fade" id="ModalForgetPassword" tabindex="-1" role="dialog" aria-labelledby="exampleForgetPassword" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleForgetPassword">
          <%= t('forget_password') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, local: true, url: password_path(resource_name), html: { method: :post, id: 'form_forget_password' }) do |f| %>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('email') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-envelope"></i>
                </div>
              </div>
              <%= f.email_field :email, class: 'form-control', autocomplete: 'email', placeholder: t('p_email'), required: true, pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', maxlength: 64, minlength: 7, id: 'form_forget_password_email', 'data-purpose' => 'email', 'aria-invalid' => 'true' %>
            </div>
          </div>
          
          <div class="col-auto text-center mt-3">
            <%= f.submit t('send'), class: "btn btn-primary w90", id: 'form_login_btn_forget_password' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <p class="w100 text-center">
          <%= t('dont_have_an_account') %> ?
          <a href="#" class="tc" data-dismiss="modal" data-toggle="modal" data-target="#ModalRegister"><br>
            <%= t('register') %>
          </a>
        </p>
        <p class="w100 text-center">
          <%= t('already_have_an_account') %> ?
          <a href="#" class="tc" data-dismiss="modal" data-toggle="modal" data-target="#ModalLogin"><br>
            <%= t('login') %>
          </a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/website/form/_login.html.erb
<!-- Modal -->
<div class="modal fade" id="ModalLogin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLogin" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLogin">
          <%= t('login') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       
      <div class="col-auto text-left mt-2">
        <% if @v_intern_company.login_user_facebook %>
        <a href="#" class="btn btn-primary w95 text-left btn-lg">
          <i class="fa fa-facebook fa-lg mr-3" aria-hidden="true"></i>
          <%#= t('login_with') %> Facebook
        </a>
        <% end %>
        <% if @v_intern_company.login_user_google %>
        <a href="#" class="btn btn-success w95 mt-2 text-left btn-lg">
          <i class="fa fa-google fa-lg mr-3" aria-hidden="true"></i>
          <%#= t('login_with') %> Google
        </a>
        <% end %>
      </div>
        
        <%= form_for(resource, as: resource_name, local: true, url: session_path(resource_name), html: { id: 'form_login' }) do |f| %>
          <div class="col-auto mt-2">
            <label class="sr-only" for="form_login_email">
              <%= t('email') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend" for="form_login_email">
                <div class="input-group-text">
                  <i class="fa fa-envelope"></i>
                </div>
              </div>
              <%= f.email_field :email, class: 'form-control', autocomplete: 'email', placeholder: t('p_email'), required: true, pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', maxlength: 64, minlength: 7, id: 'form_login_email', 'data-purpose' => 'email', 'aria-invalid' => 'true' %>
            </div>
          </div>
          <div class="col-auto">
            <label class="sr-only" for="form_login_password">
              <%= t('password') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-lock"></i>
                </div>
              </div>
              <%= f.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: t('p_password'), required: true,  pattern: '.{6,64}', maxlength: 64, minlength: 6, id: 'form_login_password', 'data-purpose' => 'password', 'aria-invalid' => 'true' %>
            </div>
          </div>
          <div class="col-auto text-center mt-3">
            <div class="form-check">
              <%= f.check_box :remember_me, id: 'form_login_remember_me' %>
              <label class="form-check-label ml-1" for="form_login_remember_me">
                <%= t('remember_me') %>
              </label>
            </div>
          </div>
          
          <div class="col-auto text-center mt-3">
            <%= f.submit t('btn_login'), class: "btn btn-primary w90", id: 'form_login_btn_login' %>
          </div>
        <% end %>
        <div class="col-auto text-center mt-3">
          <a href="#" class="tc" data-dismiss="modal" data-toggle="modal" data-target="#ModalForgetPassword">
            <%= t('forget_password') %>
          </a>
        </div>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <p>
          <%= t('dont_have_a_account') %> ?
          <a href="#" class="tc" data-dismiss="modal" data-toggle="modal" data-target="#ModalRegister">
            <%= t('register') %> 
          </a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/website/form/_profile.html.erb
<!-- Modal -->
<div class="modal fade" id="ModalProfile" tabindex="-1" role="dialog" aria-labelledby="exampleModalProfile" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalProfile">
          <%= t('profile') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, local: true, url: users_update_path, html: { id: 'form_profile', method: :put }) do |f| %>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('full_name') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-user"></i>
                </div>
              </div>
              <%= f.text_field :full_name, class: 'form-control', placeholder: t('p_full_name'), required: true, pattern: '.{3,64}', maxlength: 64, minlength: 3, id: 'form_profile_full_name', 'data-purpose' => 'full_name', 'aria-invalid' => 'true', value: current_user.full_name %>
            </div>
          </div>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('email') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-envelope"></i>
                </div>
              </div>
                <%= f.email_field :email, class: 'form-control', placeholder: t('p_email'), required: true, pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$', maxlength: 64, minlength: 7, id: 'form_profile_email', 'data-purpose' => 'email', 'aria-invalid' => 'true', value: current_user.email, 'disabled' => true %>
            </div>
          </div>
          <div class="col-auto text-center mt-3">
            <div class="form-check">
              <%= f.check_box :newsletter, class: 'form-check-input', :checked => current_user.newsletter, id: 'form_profile_newsletter' %>
              <label class="form-check-label" for="form_profile_newsletter">
                <%= t('register_newsletter') %>
              </label>
            </div>
          </div>
          
          <div class="col-auto text-center mt-3">
            <%= f.submit t('update_information_user'), class: "btn btn-primary w90", id: 'form_profil_btn_update' %>  
          </div>
          
          <div class="col-auto text-center mt-3">
            <p>
              By signing in, you agree to our 
              <%= link_to t('term_user'), term_user_path, target: '_blank', class: 'tc' %> and 
              <%= link_to t('privacy_policy'), privacy_policy_path, target: '_blank', class: 'tc' %>
            </p>
          </div>
        <% end %>
      </div>
      <div class="modal-footer justify-content-between">
        <%= form_for(resource, as: resource_name, local: true, url: registration_path(current_user), html: { method: :delete }) do |f| %>
          <%= f.submit t('delete_account'), class: 'btn btn-danger ml-auto', data: { confirm: "Are You sure ?" }, :onclick => "return confirm('Are You sure ?')" %>
        <% end %>
        <%#= link_to 'Destroy', registration_path(current_user), class: 'btn btn-danger ml-auto', method: :delete, data: { confirm: 'Are you sure?' } %>
        
        <a href="#" class="btn btn-warning t-white" data-dismiss="modal" data-toggle="modal" data-target="#ModalResetPassword">
          <%= t('change_password') %>
        </a>
        
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <%= t('close') %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/website/form/_reset_password.erb
<!-- Modal -->
<div class="modal fade" id="ModalResetPassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalResetPassword" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalResetPassword">
          <%= t('change_password') %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%#= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
        <%= form_for(resource, as: resource_name, url: user_registration_path, html: { id:  'form_reset_password', method: :put }) do |f| %>
        <%#= form_for(resource, as: resource_name, local: true, url: registration_path(resource_name), html: { :id => 'form_reset_password', method: :put }) do |f| %>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('old_password') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-lock"></i>
                </div>
              </div>
                <%= f.password_field :current_password, autocomplete: "off", class: 'form-control', required: true, placeholder: t('p_old_password'), pattern: '.{6,64}', maxlength: 64, minlength: 6, id: 'form_reset_password_old_password', 'data-purpose' => 'password', 'aria-invalid' => 'true' %>
            </div>
          </div>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('password') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-lock"></i>
                </div>
              </div>
                <%= f.password_field :password, autocomplete: "off", class: 'form-control', required: true, placeholder: t('p_password'), pattern: '.{6,64}', maxlength: 64, minlength: 6, id: 'form_reset_password_password', 'data-purpose' => 'password', 'aria-invalid' => 'true' %>
            </div>
          </div>
          <div class="col-auto">
            <label class="sr-only" for="inlineFormInputGroup">
              <%= t('confirm_password') %>
            </label>
            <div class="input-group mb-2">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fa fa-unlock"></i>
                </div>
              </div>
                <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', required: true, placeholder: t('p_confirm_password'), pattern: '.{6,64}', maxlength: 64, minlength: 6, id: 'form_reset_password_confirm_password', 'data-purpose' => 'password', 'aria-invalid' => 'true' %>
            </div>
          </div>
          
          <div class="col-auto text-center mt-3">
            <%= f.submit t('update_information_user'), class: "btn btn-primary w90", id: 'form_reset_password_btn_update' %>  
          </div>
          
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <%= t('close') %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/website/navbar/_bottom_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-lg" id="navbar">
  <%= render './layouts/shared/website/navbar/brand' %>
  <%= render './layouts/shared/website/navbar/menu' %>
</nav>

app/views/layouts/shared/website/navbar/_brand.html.erb
<%= link_to :root, :class => "navbar-brand op80", :title => "Reflow", :alt => "Reflow", 'data-purpose' => 'links-jobs-brand-logo' do %>
  <h3>Re<span>Flow</span></h3>
<% end %>

app/views/layouts/shared/website/navbar/_container_menu.html.erb
<%= render './layouts/shared/website/navbar/top_navbar' %>
<%= render './layouts/shared/website/navbar/bottom_navbar' %>

app/views/layouts/shared/website/navbar/_flags.html.erb
<div class="form-inline mt-2 mt-md-0 pull-right" id="navbarResponsive">
  <ul class="flag">
    <% @v_idioms.each do |idiom| %>
      <li class="d-inline">
        <%= link_to( idiom.url, :class => 'rounded') do %>
          <%= image_tag idiom.svg, width: 24, height: 24, alt: idiom.name, title: idiom.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/shared/website/navbar/_form_search.html.erb
<form class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="search" placeholder="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

app/views/layouts/shared/website/navbar/_logout.html.erb
<%= form_for(resource, as: resource_name, url: destroy_user_session_path, class: '', html: { method: :delete, id: 'form_logout' }) do |f| %>
  <%= f.submit t('logout'), class: 'btn btn-secondary btn-sm' %>
<% end %>

app/views/layouts/shared/website/navbar/_menu.html.erb
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
  <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

  </ul>
</div>

app/views/layouts/shared/website/navbar/_register_login.html.erb
<div class="pull-right">
  <% if ((user_signed_in?) and (@v_intern_company.register_user)) || ((admin_signed_in?) and (@v_intern_company.area_admin)) %>
    <% if (admin_signed_in?) and (@v_intern_company.area_admin) %>
      <div class="btn-group mt--4" role="group" aria-label="Basic example">
        <%= render './layouts/shared/admin/navbar/logout' %>
      </div>
    <% end %>
    <% if (user_signed_in?) and (@v_intern_company.register_user) %>
    <div class="btn-group mt--4" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#ModalProfile">
        <%= t('profile') %>
      </button>
      <%= render './layouts/shared/website/navbar/logout' %>
      <%= render './layouts/shared/website/form/profile' %>
      <%= render './layouts/shared/website/form/reset_password' %>
    </div>
    <% end %>
  <% else %>
    <div class="btn-group mt--4" role="group" aria-label="Basic example">
      <% if @v_intern_company.register_user then %>
        <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#ModalLogin">
          <%= t('login') %>
        </button>
      <% end %>
      <% if @v_intern_company.register_new_user then %>
        <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#ModalRegister">
          <%= t('register') %>
        </button>
      <% end %>
    </div>
    <% if @v_intern_company.register_user then %>
      <%= render './layouts/shared/website/form/login' %>
      <%= render './layouts/shared/website/form/forget_password' %>
    <% end %>
    <% if @v_intern_company.register_new_user then %>
      <%= render './layouts/shared/website/form/register' %>
    <% end %>
  <% end %>
</div>

app/views/layouts/shared/website/navbar/_top_navbar.html.erb
<div class="bg-dark">
  <div class="bg-light p-2 border border-bottom rounded">
    <%= render './layouts/shared/website/navbar/social_network' %>
    <%= render './layouts/shared/website/navbar/register_login' %>
  </div>
</div>